### ISSUE TITLE
Scientific Literature, Pulling Back SemMedDB Data

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#5] opened 2015-10-15 15:34 UTC
SemMedDB data has modality.  We do not want to return anything that has a modality of false.

We should get the 24 to tie out with 27.

---

![image](https://cloud.githubusercontent.com/assets/6305439/10518673/807ffae8-7330-11e5-9639-91d330a1935d.png)

**Comment by anthonysena** [comment] 2015-10-18 13:28
Fixed the root cause of this issue by filtering out the "modality = false" records via the WebAPI. Going to keep this issue open in order to focus on the UI elements.

**Comment by anthonysena** [comment] 2015-10-27 18:13
Closing this issue as we've provided a link out to PubMed. There is another issue open to address getting all of the metadata from LAERTES required to display the sci lit results in Penelope. Once that is completed, we'll revisit this section

**Closed as completed by anthonysena** 2015-10-27 18:13 UTC
Labels: Must Have
